[2023-10-22 08:11:49,490] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rate_to_postgres.wait_for_new_records manual__2023-10-22T08:11:13.670440+00:00 [queued]>
[2023-10-22 08:11:49,508] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rate_to_postgres.wait_for_new_records manual__2023-10-22T08:11:13.670440+00:00 [queued]>
[2023-10-22 08:11:49,509] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-22 08:11:49,509] {taskinstance.py:1377} INFO - Starting attempt 6 of 6
[2023-10-22 08:11:49,510] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-22 08:11:49,534] {taskinstance.py:1397} INFO - Executing <Task(SqlSensor): wait_for_new_records> on 2023-10-22 08:11:13.670440+00:00
[2023-10-22 08:11:49,543] {standard_task_runner.py:52} INFO - Started process 1128 to run task
[2023-10-22 08:11:49,554] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_to_postgres', 'wait_for_new_records', 'manual__2023-10-22T08:11:13.670440+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/get_exchange_rate.py', '--cfg-path', '/tmp/tmp59o95ccl', '--error-file', '/tmp/tmpm9ild0lw']
[2023-10-22 08:11:49,555] {standard_task_runner.py:80} INFO - Job 29: Subtask wait_for_new_records
[2023-10-22 08:11:49,672] {task_command.py:371} INFO - Running <TaskInstance: exchange_rate_to_postgres.wait_for_new_records manual__2023-10-22T08:11:13.670440+00:00 [running]> on host 1e02f9893e6c
[2023-10-22 08:11:49,799] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=andrey
AIRFLOW_CTX_DAG_ID=exchange_rate_to_postgres
AIRFLOW_CTX_TASK_ID=wait_for_new_records
AIRFLOW_CTX_EXECUTION_DATE=2023-10-22T08:11:13.670440+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-22T08:11:13.670440+00:00
[2023-10-22 08:11:49,814] {base.py:68} INFO - Using connection ID 'conn_exchange_rate' for task execution.
[2023-10-22 08:11:49,897] {sql.py:92} INFO - Poking: SELECT COUNT(*) FROM history_rate WHERE date_rate > 'None' (with parameters None)
[2023-10-22 08:11:49,907] {base.py:68} INFO - Using connection ID 'conn_exchange_rate' for task execution.
[2023-10-22 08:11:49,921] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 277, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/sql.py", line 93, in poke
    records = hook.get_records(self.sql, self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 162, in get_records
    cur.execute(sql)
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp: "None"
LINE 1: SELECT COUNT(*) FROM history_rate WHERE date_rate > 'None'
                                                            ^

[2023-10-22 08:11:49,934] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=exchange_rate_to_***, task_id=wait_for_new_records, execution_date=20231022T081113, start_date=20231022T081149, end_date=20231022T081149
[2023-10-22 08:11:49,949] {standard_task_runner.py:97} ERROR - Failed to execute job 29 for task wait_for_new_records (invalid input syntax for type timestamp: "None"
LINE 1: SELECT COUNT(*) FROM history_rate WHERE date_rate > 'None'
                                                            ^
; 1128)
[2023-10-22 08:11:49,964] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-22 08:11:50,031] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
