[2023-10-22 08:10:10,378] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rate_to_postgres.wait_for_new_records scheduled__2023-10-22T07:50:00+00:00 [queued]>
[2023-10-22 08:10:10,399] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rate_to_postgres.wait_for_new_records scheduled__2023-10-22T07:50:00+00:00 [queued]>
[2023-10-22 08:10:10,400] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-22 08:10:10,400] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2023-10-22 08:10:10,401] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-22 08:10:10,428] {taskinstance.py:1397} INFO - Executing <Task(SqlSensor): wait_for_new_records> on 2023-10-22 07:50:00+00:00
[2023-10-22 08:10:10,435] {standard_task_runner.py:52} INFO - Started process 1022 to run task
[2023-10-22 08:10:10,443] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_to_postgres', 'wait_for_new_records', 'scheduled__2023-10-22T07:50:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/get_exchange_rate.py', '--cfg-path', '/tmp/tmptytj60io', '--error-file', '/tmp/tmp4hy451j3']
[2023-10-22 08:10:10,444] {standard_task_runner.py:80} INFO - Job 12: Subtask wait_for_new_records
[2023-10-22 08:10:10,549] {task_command.py:371} INFO - Running <TaskInstance: exchange_rate_to_postgres.wait_for_new_records scheduled__2023-10-22T07:50:00+00:00 [running]> on host 1e02f9893e6c
[2023-10-22 08:10:10,691] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=andrey
AIRFLOW_CTX_DAG_ID=exchange_rate_to_postgres
AIRFLOW_CTX_TASK_ID=wait_for_new_records
AIRFLOW_CTX_EXECUTION_DATE=2023-10-22T07:50:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-22T07:50:00+00:00
[2023-10-22 08:10:10,709] {base.py:68} INFO - Using connection ID 'conn_exchange_rate' for task execution.
[2023-10-22 08:10:10,793] {sql.py:92} INFO - Poking: SELECT COUNT(*) FROM history_rate_btc_rub WHERE date_rate > 'None' (with parameters None)
[2023-10-22 08:10:10,803] {base.py:68} INFO - Using connection ID 'conn_exchange_rate' for task execution.
[2023-10-22 08:10:10,816] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 277, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/sql.py", line 93, in poke
    records = hook.get_records(self.sql, self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 162, in get_records
    cur.execute(sql)
psycopg2.errors.UndefinedTable: relation "history_rate_btc_rub" does not exist
LINE 1: SELECT COUNT(*) FROM history_rate_btc_rub WHERE date_rate > ...
                             ^

[2023-10-22 08:10:10,831] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rate_to_***, task_id=wait_for_new_records, execution_date=20231022T075000, start_date=20231022T081010, end_date=20231022T081010
[2023-10-22 08:10:10,845] {standard_task_runner.py:97} ERROR - Failed to execute job 12 for task wait_for_new_records (relation "history_rate_btc_rub" does not exist
LINE 1: SELECT COUNT(*) FROM history_rate_btc_rub WHERE date_rate > ...
                             ^
; 1022)
[2023-10-22 08:10:10,896] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-22 08:10:10,959] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
